apiVersion: skaffold/v2beta10 # latest
kind: Config
metadata:
  name: alt-poll
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: jsaleem/alt-poll-auth
      context: ./auth
    - image: jsaleem/alt-poll-polls
      context: ./polls
  local:
    push: true

deploy:
  helm:
    releases:
      - name: alt-poll
        # artifactOverrides:
        #   image: jsaleem/alt-poll-auth
        # Skaffold continuously tags your image, so no need to put one here.
        chartPath: /Users/joelsaleem/Documents/GitHub/alt-poll/alt
        # valuesFile: /Users/joelsaleem/Documents/GitHub/alt-poll/alt/values.yaml
        setValues:
          auth.postgresqlPassword: foobar
        recreatePods: true
        skipBuildDependencies: true
    # flags:
    #   upgrade:
    #     - --set
    # - "--set auth.postgresqlPassword=foobar"
