---
# Source: postgres/templates/secureconfig.yaml
apiVersion: v1
kind: Secret
metadata:
  name: auth-db-postgres
  labels:
    helm.sh/chart: postgres-0.2.0
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: auth-db
    app.kubernetes.io/version: "13.1"
    app.kubernetes.io/managed-by: Helm
stringData:
  POSTGRES_PASSWORD: 0LLReqnO9Y
  POSTGRES_USER: "postgres"
  POSTGRES_HOST_AUTH_METHOD: md5
---
# Source: postgres/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: auth-db-postgres
  labels:
    helm.sh/chart: postgres-0.2.0
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: auth-db
    app.kubernetes.io/version: "13.1"
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: auth-db
---
# Source: postgres/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db-postgres
  labels:
    helm.sh/chart: postgres-0.2.0
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: auth-db
    app.kubernetes.io/version: "13.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  serviceName: auth-db-postgres
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/instance: auth-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: auth-db
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
          image: "postgres:13.1"
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pg
          envFrom:
            - secretRef:
                name: auth-db-postgres
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -h localhost
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -h localhost
            initialDelaySeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
          resources:
            {}
          volumeMounts:
            - mountPath: /var/run
              name: run
            - mountPath: /tmp
              name: tmp
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      nodeSelector:
        kubernetes.io/arch: amd64
      volumes:
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: postgres-data
          emptyDir: {}
