apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-svc
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth-depl
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: jsaleem/alt-poll-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef: 
                  name: google-client
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef: 
                  name: google-client
                  key: GOOGLE_CLIENT_SECRET
