apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-client-svc
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client-depl
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client 
          image: jsaleem/alt-poll-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000