apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-svc
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth-depl
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth 
          image: jsaleem/alt-poll-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PG_HOST
              value: postgres://myuser:mypassword@postgres:5432/auth
            - name: PG_PORT
              value: 5432
            - name: RABBIT_HOSTNAME
              value: amqp://admin:password@rabbitmq:5672
            - name: RABBIT_USERNAME
              value: admin
            - name: RABBIT_PASSWORD
              value: password
            - name: RABBIT_PORT
              value: 5672
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef: 
                  name: google-client
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef: 
                  name: google-client
                  key: GOOGLE_CLIENT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_SECRET
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: auth-db-password
                  key: DB_PASSWORD
